name: Build and Run OpenAiCodeReview By Main Maven Jar

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build with Maven
        run: mvn clean install

      - name: Copy code-review-sdk JAR
        run: |
          mkdir -p ./libs
          cp ./code-review-sdk/target/*.jar ./libs/

      - name: Run Code Review
        run: java -jar ./libs/code-review-sdk-1.0.jar
